### ISSUE TITLE
2.0 Roadmap

### ISSUE THREAD

**Issue by silentcloud** [ant-design/ant-design-mobile#1274]
##  antd-mobile@2.0
- [1.x roadmap](https://github.com/ant-design/ant-design-mobile/issues/821)
- [2.0 milestone](https://github.com/ant-design/ant-design-mobile/milestone/5)
- [2.0 project](https://github.com/ant-design/ant-design-mobile/projects/2)

[antd-moble@2.0](https://github.com/ant-design/ant-design-mobile/projects/2) 的主题是面向 c 端业务的轻量化与易用性，包括如下几个大的计划：

- 去除社区的重量级依赖 moment.js 和 hammer.js， 对日期和手势相关的组件统一重写。[#1565](https://github.com/ant-design/ant-design-mobile/issues/1565), [#1217](https://github.com/ant-design/ant-design-mobile/issues/1217)
- 评估部分 rc-component 需要拆分移动版，不再与 antd 使用公共的底层依赖，因为 pc 组件有键盘访问，鼠标事件等 mobile 用不到的特性，交互和功能也有一定冗余，而目前也没有做好模块化和按需加载。[#1625](https://github.com/ant-design/ant-design-mobile/issues/1625)
- 简化配置，并做好脚手架与模板。[#1575](https://github.com/ant-design/ant-design-mobile/issues/1575) [#1557](https://github.com/ant-design/ant-design-mobile/issues/1557)
- 暂定目标是组件库 **兼容** preact的一些实现 bug。

## branch
    - https://github.com/ant-design/ant-design-mobile/tree/master -> 2.x
    - https://github.com/ant-design/ant-design-mobile/tree/1.x -> 1.x

## 1.x 
- [x] 国际化翻译 #329 @ant-design/ant-design-team 
- [ ] 测试用例，功能测试 (先主要补充点击回调函数的测试)  @ant-design/ant-design-team 
    - [x] Button / SearchBar / NoticeBar @warmhug
    - [ ] Grid / InputItem / TextareaItem / List  @pingan1927 
    - [x] SegmentedControl / Switch / Tag / Carousel (RN 缺失，Web 在底层组件已有测试)  @silentcloud 
- [x] React@16 支持 #1118 @paranoidjk 
- [ ] SSR 完全支持  #1059 @cncolder @paranoidjk
- [ ] 出一个和 eggjs 配合使用做 server render 的官方示例 @paranoidjk
- [ ] 【待讨论】按需加载：动态加载，卸载业务模块。没有构建环节。
- [x] bundle size 的统计和 ci @warmhug @paranoidjk 
    - [Size and dependency analysis](https://ant-design.github.io/ant-design-analysis/#antd-mobile/versions/1.4.1)

## 2.0 
- [x] 底层组件拆分，按需加载，检查用到的 pc 组件
- [x] webpack 2/3 的  Tree-shaking 使用
    - 含业务中使用、需要 antd-tools/atool-build 升级 webpack3.  @yesmeck 
- [x] 简化配置和使用 https://github.com/ant-design/ant-design-mobile/issues/1557 @paranoidjk
- [ ] 提供升级工具（内部业务尽量消除版本碎片化、可人工帮业务升级）
- 
- [x] preact 支持 #1267  
- [x] momentjs 做成可选依赖  #1217  @warmhug 
- [x] nuka-carousel  #1254 ~~能否和 PC 共同维护一个~~ @warmhug
- [x] rc-tabs  优化 #1287 
- [x] Popup / ActionSheet / Modal  变更 #1125  @paranoidjk
- [x] DatePicker / Picker 变更 #1036  @paranoidjk
- [ ] 基于 react-infinity 封装 table-view @paranoidjk
- [x] 抽离 pull2refresh @paranoidjk
- [x] Range DatePicker #1232 
- [x] 新增 日历 组件 #1610 [gitlab#496](http://gitlab.alibaba-xxx.com/react-ui/ant-mobile/issues/496) @扬远
-
- [ ] react-native-menu  #1269  @silentcloud 
- [ ] RN 组件补全（补充`Menu`、`Range`）@silentcloud
- [ ] RN 组件和 Web 组件 APIs 和表现最大化一致  @silentcloud 
- [ ] 网站展示 RN demo #1075 

## 交互视觉 && design

- [ ] 动画方式、动画流畅度。
    - Tabs / Carousel / Accordion
- [ ] 视觉需要按照钱包10.0.8样式做一个升级，同时校验底层样式库（designtokens）的合理性。
- [ ] DesignLab：有部分 Mobile 相关的模板，可以在 DesignLab 生产和消费，这个优先级可以往后推 @silentcloud 
- [x] 根据业务线反馈，优化组件，谨慎添加组件。
- [ ] Axure 、Sketch 资源库对外发布

## 目标

- **最大限度的“减小体积、减少依赖、提升性能”，做到真正好的支持面向 C 端的业务**，给出包大小的优化、性能优化等的”明确数据对比“出来。
- (能更有底气的) **对外宣传推广，提升影响力**。(思考更进一步创新)

时间点

- 1.x 估计还需要 `3 个月` 时间迭代。
- 2.0 alpha / beta 版本需要迭代 `1 - 1.5 个月`， 2.0 正式版发布时间预计`9月底`。

**Comment by Lyndon001** [comment]
### antd-mobile `石油`
- design token 优化：从强行适配多个 BU，聚焦到适配 支付宝 生态圈为核心，提供能力到其他 BU 即可
- 组件能力：持续优化，谨慎添加。不是越多越好
- 小程序：

### 站点`油桶`
- mobile.ant.design:
- design.alipay.com：
- 设计师平台：

### 工具`挖油机`
- DesignLab：有部分 Mobile 相关的模板，可以在 DesignLab 生产和消费，这个优先级可以往后推

**Comment by silentcloud** [comment]
>  DesignLab：有部分 Mobile 相关的模板，可以在 DesignLab 生产和消费，这个优先级可以往后推

这个由我来推，我跟组内衔接比较方便

**Comment by warmhug** [comment]
> 以下列出个人建议

1.x 工作

- 所有文档的翻译、组件测试用例，建议在 1.x 里全部完成。
- RN 组件还缺少 `Table`、`NavBar`、`Menu`、`Range`四个，建议只用补下`Menu`、`Range`即可、建议在 1.x 里完成。
- RN 组件和 Web 组件 api 和表现最大化一致，1.x 里完成 80%，剩下的在 2.0 迭代里随着部分 web 组件变更一起全部完成。

> ref https://github.com/ant-design/ant-design-mobile/issues/821

2.0 重点

- **最大限度的“减小体积、减少依赖、提升性能”，做到真正好的支持面向 C 端的业务**，不再被抱怨体积大，给出包大小的优化、性能优化等的”明确数据对比“出来。
- (要能更有底气的) **对外宣传，积极推广，提升影响力**。(同时思考怎么能有更进一步的创新、产生爆点)

时间点

- 1.x 考虑新增的工作量、日常bug维护等，估计还需要 `3 个月` 时间迭代。
- 1.x 迭代后期会并行进入 2.0 的开发，完成 2.0 所有主功能的开发进入 alpha 版本时间点 `3.5 - 4 个月后`。
- 2.0 alpha / beta 版本需要迭代 `1 - 1.5 个月`， 2.0 正式版发布时间预计`5 个月`后。

**Comment by silentcloud** [comment]
> RN 组件和 Web 组件 api 和表现最大化一致，1.x 里完成 80%，剩下的在 2.0 迭代里随着部分 web 组件变更一起全部完成。  

这个到时候估计有部分 api 变动，能做的在 1.x 里做掉好了

> 2.0 正式版发布时间预计5 个月后

这个最好是能够在 Q1、Q2（也就是 9月底） 有一个初步的版本（比如 beta、alpha）

**Comment by afc163** [comment]
搞一个 bundle size 的标准和 ci 出来。

**Comment by warmhug** [comment]
需要优化 或 fork 单独维护的复杂组件：

- [ ] momentjs  #1217 
- [ ] rc-tabs  #1287
- [ ] react-native-menu  #1269
- [ ] nuka-carousel  #1254 能否和 PC 共同维护一个

重构优化

- [ ] Popup / ActionSheet / Modal #1125
- [ ] DatePicker / Picker #1036 #1232
- [ ] 网站展示 RN demo #1075

**Comment by pingan1927** [comment]
[ ] 按需加载：动态加载，卸载业务模块。没有构建环节。

**Comment by warmhug** [comment]
## Bundle Size 记录
> 基于 [web-webpack sample](https://github.com/ant-design/antd-mobile-samples/tree/master/web-webpack) 的 [webpack-bundle-analyzer](https://www.npmjs.com/package/webpack-bundle-analyzer) 统计结果。这里记录主要模块的大小

### 1.1.3 (Stat size)
- 常用强依赖: rmc-list-view 87.4k + zscroller 53.7k > moment 126k > hammerjs 72k > rc-tabs 40k > nuka-carousel 31.6k > rc-touchable 24.3k > rc-animate 20k+ 
- 非强依赖: rc-form + deps ~= 100k

**Comment by paranoidjk** [comment]
@warmhug  https://github.com/ant-design/antd-tools/issues/42 这个可以分析看看

**Comment by yiminghe** [comment]
全部 模块切换到 es 2015

https://github.com/react-component/react-component.github.io/issues/12

https://github.com/ant-design/antd-tools/pull/40

**Comment by paranoidjk** [comment]
@warmhug  分析项目 bundle 时候发现 antd-mobile 很多复杂组件都是全打包， 比如 ListView

<img width="400" height="400" src="https://zos.alipayobjects.com/rmsportal/juIoOAlPPgeRZmYkWNoN.png">


- [ ] 底层组件拆分， 在 API 友好和体积上做个权衡，比如 ListView 目前没有按需加载 https://github.com/react-component/m-list-view/blob/master/src/index.js#L7
- [ ] 或者寄希望于升级到 webpack 2 之后的  Tree-shaking

**Comment by paranoidjk** [comment]
- [ ] carousel 滑动手势不灵敏且无法开放控制，进而导致 Grid[mode=carousel] 无法控制
- [ ] tabs 切换会露白底
- [ ] listview 中集成横滑组件（swipeAction）, 手势冲突

**Comment by paranoidjk** [comment]
@warmhug 
https://github.com/robertknight/webpack-bundle-size-analyzer#important-note-about-minified-code

**Comment by silentcloud** [comment]
整理各个组件的 style， https://github.com/ant-design/ant-design-mobile/issues/1380

**Comment by paranoidjk** [comment]
@pingan1927 上拉加载的，把对应的同学拉进这个 issue 吧

**Comment by paranoidjk** [comment]
- [ ] 新增高清方案配置集成， 简化文档 https://github.com/ant-design/ant-design-mobile/issues/1515 @paranoidjk

**Comment by afc163** [comment]
https://github.com/siddharthkp/bundlesize

**Comment by paranoidjk** [comment]
https://github.com/facebook/react/pull/10090

**Comment by paranoidjk** [comment]
# antd-mobile@2.0

[antd-moble@2.0](https://github.com/ant-design/ant-design-mobile/projects/2) 的主题是轻量化与易用性，包括如下几个大的计划：

- 去除社区的重量级依赖 moment.js 和 hammer.js， 对日期和手势相关的组件统一重写。[#1565](https://github.com/ant-design/ant-design-mobile/issues/1565), [#1217](https://github.com/ant-design/ant-design-mobile/issues/1217)
- 评估部分 rc-component 需要拆分移动版，不再与 antd 使用公共的底层依赖，因为 pc 组件有键盘访问，鼠标事件等 mobile 用不到的特性，交互和功能也有一定冗余，而目前也没有做好模块化和按需加载。[#1625](https://github.com/ant-design/ant-design-mobile/issues/1625)
- 简化配置，并做好脚手架与模板。[#1575](https://github.com/ant-design/ant-design-mobile/issues/1575) [#1557](https://github.com/ant-design/ant-design-mobile/issues/1557)
- 暂定目标是组件库 **兼容** preact的一些实现 bug。

**Comment by paranoidjk** [comment]
# 关于 preact

- **体积**
  - [react.production.min.js@16.0.0-beta.1](https://unpkg.com/react@16.0.0-beta.1/umd/react.production.min.js@16.0.0-beta.1) + [react-dom.production.min.js ](https://unpkg.com/react-dom@16.0.0-beta.1/umd/react-dom.production.min.js ) = 6.73kb + 121.48kb = `128.21 kb`


  - [preact.min.js](https://unpkg.com/preact@8.2.1/dist/preact.min.js) + [preact-compat.min.js](https://unpkg.com/preact-compat@3.16.0/dist/preact-compat.min.js) = 8.28 + 9.08 = `17.36kb`

  - [vue.runtime.min.js](https://unpkg.com/vue@2.4.2/dist/vue.runtime.min.js): `58.4kb` (运行时，需要将模板预编译)

  - [vue.min.js](https://unpkg.com/vue@2.4.2/dist/vue.min.js): 81.83kb (完整版，包含模板编译器和运行时)


    综合下来，react 核心其实已经最小，但对业务而言，因为 react-dom 超级大，所以整个 react 方案会比 vue 预编译的方案大 `70kb`, 比 preact 大 `110kb`。

- **性能**
  - 结合 @warmhug  的 benchmark, preact 貌似是不错的选择。

- **兼容性，可维护性**
  - 事实上 antd-mobile 也在配合口碑的需求做对preact的支持，这个过程中是发现不少问题的。


我的顾虑主要是两点:

- **收益与风险同在**： preact 没有通过 react 全部测试用例，潜在的坑很难确定有多少。
- **是否可持续发展**： react fiber preact 是否会跟进？比如前两天发布的 react 16 第一个 beta 版新增的 [comoponentDidCatch](https://facebook.github.io/react/blog/2017/07/26/error-handling-in-react-16.html) 。长远来看，react 团队肯定是继续向前发展的，preact 的开发者就一个人，真的能做到一直保持 **用极少的代码重写并实现 react 的大部分 api** ？ 我持怀疑态度。

**Comment by okoala** [comment]
其实我在想，现在应用一般都是跑在一个容器内的，是否直接可以内置 React~

**Comment by paranoidjk** [comment]
@okoala 这种方案也是有的，比如钱包就有全局的预埋离线资源包，是有内置 react 这些公共资源的。不过毕竟场景受限于容器，作为组件库还是需要尽力精简自身。

**Comment by szwork2013** [comment]
@paranoidjk  antd-mobile 2 计划支持android终端的最低版本是多少？目前antd-mobile 2.0.0-alpha.9通过webpack3，或roadhg+dva等脚手架测试项目在android4.1,4.3的版本下均显示空白，但是访问直接访问
http://beta.mobile.ant.design/kitchen-sink没有问题，似乎autoprefixer没有起作用，autoprefixer: {
browsers: [
"iOS >= 8", "Android >= 4"
]

**Comment by benjycui** [comment]
android 各版本系统占比 https://mtj.baidu.com/data/mobile/device
