### ISSUE TITLE
[PREACT] antd-mobile适配Preact 问题收集

### ISSUE THREAD

**Issue by pingan1927** [ant-design/ant-design-mobile#1304]
* [x] `SegmentedControl`：针对style对象css值为`undefined`处理不一致。#1374
* [x] `ImagePicker`: 如果选择图片的dom切换到下一行，`input`的`onChange`事件脚本报错。#1487
* [x] `Picker`: 如果数据是异步加载，`children.map`报错。[#28 m-picker](https://github.com/react-component/m-picker/pull/28)
* [ ] ~~`Range`: 不可用。~~ 业务使用场景小，成本大，暂不适配
* [ ] ~~`Slider`:  不可用。~~ 业务使用场景小，成本大，暂不适配
* [ ] `Modal`: 点击关闭无效。 麦督在跟进.
* [ ] `代码框`: 弹出后就无法关闭
* [ ] `tabs `: 报错? 已pr [#76 rc-tabs](https://github.com/react-component/tabs/pull/76)
* [ ] `Picker`: 底层组件重构，需要重新适配

**Comment by afc163** [comment]
#1267

**Comment by paranoidjk** [comment]
close. 

- snapshot 结果在这 https://github.com/ant-design/ant-design-mobile/pull/1306
- 如群里讨论所说，antd-mobile 无需主动适配，所有的工作在 [preact-compat](https://github.com/developit/preact-compat) 这一层。
- 与其他库结合使用或者深层问题只能业务 case by case 的发现或解决。

**Comment by pingan1927** [comment]
这个issue主要就是集中记录case by case每个组件可能产生的问题。以及配合常用模块可能遇到的问题。

**Comment by afc163** [comment]
- https://github.com/developit/preact/pull/699
- https://github.com/developit/preact/issues/615

**Comment by ckken** [comment]
preact 加入 ant-mobile 的 tab后报错：
```
preact.js?f2a4:66 Uncaught TypeError: value is not a function
    at setAccessor (preact.js?f2a4:66)
    at diffAttributes (preact.js?f2a4:203)
    at idiff (preact.js?f2a4:148)
    at innerDiffNode (preact.js?f2a4:178)
    at idiff (preact.js?f2a4:147)
    at diff (preact.js?f2a4:110)
    at renderComponent (preact.js?f2a4:284)
    at setComponentProps (preact.js?f2a4:244)
    at buildComponentFromVNode (preact.js?f2a4:331)
    at idiff (preact.js?f2a4:134)
```

**Comment by paranoidjk** [comment]
@ckken You should provide your demo code at least

**Comment by silentcloud** [comment]
@pingan1927 
- Modal: 点击关闭无效。 麦督在跟进.

这个我在 2.0 master 上 ok

![show](https://user-images.githubusercontent.com/1698185/29701593-2989fb6c-899f-11e7-9ee7-92a477cd3a11.gif)

**Comment by pingan1927** [comment]
@paranoidjk 麦督 私下找你

**Comment by paranoidjk** [comment]
@silentcloud 把 preact 相关的问题集中到这一个 issue 里。

**Comment by silentcloud** [comment]
统一链接到  #1631 里好了
