### ISSUE TITLE
0.9 release

### ISSUE THREAD

**Issue by foriacus** [ant-design/ant-design-mobile#160]
### 计划 
- dealine `9月23日` 
- 发布时间 `9月30日`

### RN组件

- [ ] grid @benjycui 

- [ ] menu @afc163 

- [ ] accordion @linfaxin 

- [ ] result @linfaxin 

### web组件
- [x] listview refreshcontrol api 调整 https://github.com/ant-design/ant-design-mobile/issues/242 @warmhug 

- [ ] 各组件 touch feedback 状态修复 #195  

- [ ] modal全屏模式新增实际场景 (gitlab #235 (comment 2947454))

- [x] List api 调整 https://github.com/ant-design/ant-design-mobile/issues/257

### demo App

- [x] demo app rn 组件分类按照 web app 同样划分 @silentcloud

### website

- [ ] 网站去除冗余代码 https://github.com/ant-design/ant-design-mobile/issues/243 @benjycui 

### 测试反馈

**Comment by silentcloud** [comment]
1.0 需要实现的 rn 组件：

- [ ] Result
- [ ] Accordion

**Comment by afc163** [comment]
没有时间做了。。

**Comment by benjycui** [comment]
rn-grid 的 CI 过了 https://github.com/ant-design/ant-design-mobile/commit/0b7dda7072d71c8d844b6ea8a9cc8a70bfc47c6b

不过新增的 API 还没做。

**Comment by silentcloud** [comment]
- [x] Card 新增通栏样式
