### ISSUE TITLE
Translation into english

### ISSUE THREAD

**Issue by MichaelSavin** [ant-design/ant-design-mobile#329]
Could you help with translation:
- all wiki pages
- [development.md](https://github.com/ant-design/ant-design-mobile/blob/master/development.md)

---

Updated from maintainers:

## Volunteer Wanted

Hey, guys! We are going to provide English documentation. 

But we are short of staff :-( So, we want some volunteers to help us to translate `antd-mobile`'s documentation into English. Every translation task needs a translator and a reviewer. Both of them are expected that they had used the component(`Menu` `Drawer` etc...) in real world.

### Translator

A translator should be familiar with both Chinese and English. 

If you want to be a volunteer translator, just comment this issue. For example, "I want to be the translator of button and modal ....". And then, we will update this issue(e.g. button (translator: @benjycui, reviewer:  @waywardmonkeys )), and ping you. 

Contributing:
1. Fork [ant-design-mobile](https://github.com/ant-design/ant-design-mobile) and `git clone`
2. Create a branch starting at `master` and name it as `translation-button`
3. `npm install && npm start`, see: [Development](https://github.com/ant-design/ant-design/wiki/Development)
4. Find Markdown files under `components/xxx`(xxx is the component which you need to translate), `index.md` and `demo/*.md` use different format, see: https://github.com/ant-design/ant-design/issues/1423
5. Just translate it, and you had better read our [advice](https://github.com/ant-design/ant-design/issues/1471#issuecomment-213636139) first.
6. Create a pull request to `ant-design-mobile:master` when your translation is done, and ping your reviewer.
7. PR will be merged, if your reviewer think it is OK.

See: 
- https://github.com/ant-design/ant-design/tree/master/components/button
- https://github.com/ant-design/ant-design/blob/master/components/button/demo/basic.md
### Reviewer

A reviewer should be a native English speaker.

If you want to be a volunteer reviewer, just comment this issue. For example, "I want to be the reviewer of button and alert...". And then, we will update this issue(e.g. button (translator: @benjycui, reviewer:  @waywardmonkeys )), and ping you. 

After your corresponding translator finish his/her work, you should review and provide some advice.

Example: https://github.com/ant-design/ant-design/pull/1932

### TODOs

- [x] development.md @paranoidjk

/docs/react
- [x] getting-started.md      @warmhug   
- [x] introduce.md            @warmhug         
- [x] practical-projects.md      @warmhug   
- [x] upgrade-notes.md

/components
- [x] checkbox     @paranoidjk      
- [x] grid @liqi07               
- [x] locale-provider @liqi07    
- [x] search-bar      @warmhug
- [x] switch          @iyutao   
- [x] toast @iyutao
- [x] accordion          @warmhug           
- [x] icon              
- [x] menu               @yesmeck 
- [x] popover            @warmhug
- [x] segmented-control   @silentcloud
- [x] tab-bar   @zhang740                     
- [x] action-sheet       @warmhug
- [x] create-tooltip     
- [x] image-picker       @silentcloud 
- [x] modal            @lixiaoyang1992  
- [x] popup               @warmhug
- [x] slider              @silentcloud
- [x] table              
- [x] activity-indicator  @silentcloud
- [x] date-picker         @warmhug
- [x] nav-bar              @warmhug  
- [x] progress           @afc163 
- [x] stepper            @silentcloud
- [x] tabs            @silentcloud
- [x] uploader @afc163 
- [x] badge @afc163         
- [x] drawer @yesmeck 
- [x] notice-bar         @ddcat1115
- [x] radio              @ddcat1115
- [x] steps              @ddcat1115
- [x] tag                @ddcat1115
- [x] button         @warmhug
- [x] input-item      @silentcloud          
- [x] range    @silentcloud
- [x] card         @silentcloud      
- [x] flex @zhang740               
- [x] list              @silentcloud
- [x] pagination         @slientcloud
- [x] refresh-control        @warmhug
- [x] textarea-item      @silentcloud
- [x] carousel           @silentcloud
- [x] list-view           @warmhug
- [x] picker              @warmhug
- [x] picker-view     @warmhug    
- [x] result             @afc163 
- [x] swipe-action       @silentcloud
- [x]  white-space / wing-blank     @warmhug

> Update by @paranoidjk

## Start to Translate :tada: :tada:

Since https://github.com/ant-design/ant-design-mobile/pull/907 had been merged to master. The  next step is to translate.

**We need help, please feel free to open a Pull Request**  😄 

## How to ?
```bash
git clone git@github.com:ant-design/ant-design-mobile.git
cd antd-mobile
npm install
npm start
```

Then open `http://127.0.0.1:8001` on your favorite  browser, you will see that the default language of the site had been changed to English.
> - but the homepage will auto detect your system language
> - and still you can switch to Chinese by click the button on the upper right corner of page

## Tasks

1.  [x] all files which extension name is `.en-US.md` should be translate to English.
    > include `components/{foo}/index.md`,  and `/doc/react/{bar}.md` , and `wiki page`      
    > right now the content of foo.en-US.md  is just a copy of it's Chinese version  foo.zh-CN.md
     
2. [x] all `components/{foo}/demo/{bar}.md` should change it's title syntax. 
     > see [Flex](https://github.com/ant-design/ant-design-mobile/blob/master/components/flex/demo/basic.md) or [CheckboxItem](https://github.com/ant-design/ant-design-mobile/blob/master/components/checkbox/index.en-US.md) as a example

cc @ant-design/ant-design-team

**Comment by belohlavek** [comment]
English translation would be amazing!

**Comment by warmhug** [comment]
Perhaps in doing this after October 31. In addition, can you help us do it.

**Comment by belohlavek** [comment]
I would be glad to help with spelling mistakes (in English), but I don't speak Chinese! 😅

**Comment by yiminghe** [comment]
@benjycui will be responsible for this

**Comment by benjycui** [comment]
Will do this after 1.0 is published, for API is unstable now.

**Comment by ecerroni** [comment]
Any ETA for this translation?

**Comment by paranoidjk** [comment]
we will working on english documentation in the next few month.
ref https://github.com/ant-design/ant-design-mobile/pull/901
- [ ] drawer 
- [ ] menu 
- [ ] nav-bar 
- [ ] pagination 
- [ ] popover 
- [ ] segmented-control 
- [ ] tabs 
- [ ] tab-bar 
- [ ] button 
- [ ] checkbox 
- [ ] date-picker 
- [ ] input-item 
- [ ] image-picker 
- [ ] picker 
- [ ] picker-view 
- [ ] radio 
- [ ] range 
- [ ] switch 
- [ ] search-bar 
- [ ] slider 
- [ ] stepper 
- [ ] textarea-item 
- [ ] accordion 
- [ ] badge 
- [ ] carousel 
- [ ] card 
- [ ] grid 
- [ ] icon 
- [ ] list 
- [ ] notice-bar 
- [ ] steps 
- [ ] table 
- [ ] tag 
- [ ] action-sheet 
- [ ] activity-indicator 
- [ ] modal 
- [ ] progress 
- [ ] popup 
- [ ] toast 
- [ ] refresh-control 
- [ ] swipe-action 
- [ ] list-view 
- [ ] result 
- [ ] locale-provider 
- [ ] flex 
- [ ] wing-blank 
- [ ] white-space

**Comment by benjycui** [comment]
Updated task list to @MichaelSavin 's comment

@paranoidjk we should try to translate on or two components' documentation to make sure mobile.ant.design is ready.

**Comment by paranoidjk** [comment]
@benjycui ok,  i will try it right now.

**Comment by paranoidjk** [comment]
## Start to Translate :tada: :tada:

Since https://github.com/ant-design/ant-design-mobile/pull/907 had been merged to master. The  next step is to translate.

**We need help, please feel free to open a Pull Request**  😄 

## How to ?
```bash
git clone git@github.com:ant-design/ant-design-mobile.git
cd antd-mobile
npm install
npm start
```

Then open `http://127.0.0.1:8001` on your favorite  browser, you will see that the default language of the site had been changed to English,  but still you can switch to Chinese by click the button on the upper right corner of page.

## Tasks

1.  [ ] all files which extension name is `.en-US.md` should be translate to English.
    > include `components/{foo}/index.md`,  and `/doc/react/{bar}.md` , and `wiki page`      
    > right now the content of foo.en-US.md  is just a copy of it's Chinese version  foo.zh-CN.md
     
2. [ ] all `components/{foo}/demo/{bar}.md` should change it's title syntax. 
     > see [Flex](https://github.com/ant-design/ant-design-mobile/blob/master/components/flex/demo/basic.md) as a example

cc @ant-design/ant-design-team

**Comment by afc163** [comment]
I call uploader and badge

**Comment by yesmeck** [comment]
I'll work on drawer and menu.

**Comment by ddcat1115** [comment]
steps & tag ~

**Comment by iyutao** [comment]
switch & toast

**Comment by lixiaoyang1992** [comment]
I want to be the translator of modal.

**Comment by yesmeck** [comment]
有些公共的词是不是约定下，比如 `prop` 在 `antd`  文档里叫"属性"， 这里叫"成员"。

**Comment by paranoidjk** [comment]
@yesmeck `props --> 属性`， follow the antd convention

**Comment by afc163** [comment]
I call progress result

**Comment by benjycui** [comment]
Could someone help us to translate intl-example? ant-design/intl-example#13

**Comment by warmhug** [comment]
@iyutao 这里翻译还要做吗？

**Comment by paranoidjk** [comment]
cc @zhang740

**Comment by silentcloud** [comment]
All work have been done.
