### ISSUE TITLE
1.x Roadmap

### ISSUE THREAD

**Issue by warmhug** [ant-design/ant-design-mobile#821]
- 国际化
- 测试完善
- 性能优化
- 业务/新技术示例覆盖完善 (https://github.com/ant-design/antd-mobile-samples)

**Comment by paranoidjk** [comment]
内置文案的国际化在 #820 已经搞了，虽然没有覆盖所以组件，但模式是通的，这个可以在1.0上

文档和网站的国际化就是个大工程了，要大家一起翻译

**Comment by paranoidjk** [comment]
1.0 release之后的迭代策略可以参考 antd 的https://github.com/ant-design/ant-design/commit/bace209d52a8fb256e25f519ce90d8e84a80d193

**Comment by paranoidjk** [comment]
备注一下

- RN 的国际化问题
- 默认语言切英文

**Comment by afc163** [comment]
中间版本不要有 break change

**Comment by paranoidjk** [comment]
- `stepper` 支持 icon，关联 gitlab `#442`

**Comment by yesmeck** [comment]
测试和性能相关的我也参与一下吧。

**Comment by benjycui** [comment]
> 默认语言是否切英文？坑在哪？ @benjycui

不兼容升级，放到 2.0 吧。

主要是现在时间类组件的 locales 分散在 moment 和 LocaleProvider 里，而这两个东西的默认语言又不一样，比较反直觉，然后在组件这层也难以处理。

**Comment by iyutao** [comment]
业务/新技术示例覆盖完善我参与

**Comment by paranoidjk** [comment]
@iyutao https://github.com/ant-design/ant-design-mobile/issues/824 这一个不紧急，有空的话也可以去参与一把

**Comment by iyutao** [comment]
OK

**Comment by warmhug** [comment]
优化：

- [ ] 使用 https://github.com/svg/svgo 优化 svg 图片
- [ ] 组件性能优化 [todos](https://github.com/ant-design/antd-mobile-samples/tree/master/web-performance#todos)

**Comment by silentcloud** [comment]
- [ ] RN 组件自定义样式 ( 单组件 & 自定义 theme)

**Comment by silentcloud** [comment]
- [ ] 复查所有 RN 组件，改造 style/index.tsx 以支持单个自定义样式

**Comment by paranoidjk** [comment]
@warmhug  微信的这个方案也是用 svgo [weflow](https://github.com/weixin/tmt-workflow/wiki/%E2%92%9A-SVG%E6%95%B4%E4%BD%93%E8%A7%A3%E5%86%B3%E6%96%B9%E6%A1%88#%E6%B3%A8%E6%84%8F%E7%82%B9)

不过他们约定了默认目录为 `src/img/`，看起来使用更简单一点

**Comment by paranoidjk** [comment]
- 这周五会发布 1.1.0： https://github.com/ant-design/ant-design-mobile/pull/1167
- 这个 issue 里面未完成的作为 1.2.0  的 roadmap 往后延。

**Comment by paranoidjk** [comment]
cc  @cncolder @bccsafe

**Comment by cncolder** [comment]
SSR原定1.1是来不及了，之前是以通过node测试为目标，现在是以支持bisheng为目标。

**Comment by benjycui** [comment]
SSR 的问题，找个 issue 总结一下，然后 assignee 里面也加下我吧。我明天看看。
